# docker-compose.yml
version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5431:5432'
    volumes:
      - task_manager-db:/var/lib/postgresql/data

  task_manager:
    build:
      context: .
    ports:
      - '4000:4000'
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    
        
volumes:
  task_manager-db: